language: rust
sudo: required
cache:
  - directories:
    - openfst-1.7.2
rust:
  - stable
#  - beta
#  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

env:
- RUST_BACKTRACE=1
script: ./.travis.sh

before_install:
  - sudo apt-get update
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get install python3.6
  - wget https://github.com/sharkdp/hyperfine/releases/download/v1.6.0/hyperfine_1.6.0_amd64.deb
  - sudo dpkg -i hyperfine_1.6.0_amd64.deb

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - libssl-dev
      - rpl

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
  fi
  rm -rf /home/travis/.cargo/registry

after_success: |
   if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    # Uncomment the following line for coveralls.io
     cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

    # Uncomment the following two lines create and upload a report for codecov.io
     cargo tarpaulin --out Xml
     bash <(curl -s https://codecov.io/bash)
   fi
