[package]
name = "rustfst-cli"
version = "1.2.4"
authors = ["Garvys <alexandre.caulier@orange.fr>"]
edition = "2018"

[dependencies]
anyhow = '1.0'
clap = "4.5"
colored = "2.1"
env_logger = "0.10"
exitcode = "1.1"
log = "0.4"
rustfst = {path = "../rustfst"}
unsafe_unwrap = "0.1"
